# Data Structure:

See more in [Python Docs](https://docs.python.org/3/tutorial/datastructures.html)

In **Python**, there are several approaches to manage data; how data is organized has a direct impact in one's routine (algorithm).
Data is always handled by means of different structure types - called **variables**


# Variable Classifications

* Per Mutability

* Per Derivation (**primitive-types** and **non-primitive-types**)



---



---



---




## 1) **Primitive Types**


a)   Strings

b)   Integers (Inteiros)

c)   Float (fracionários)

d)   Boolean

**Observation**: Primitives store only one information per type.

### **String** Type


In [ ]:
I_am_String = 'Hi! My name is Philipe'

print(I_am_String)

Hi! My name is Philipe


Mais exemplos: [veja aqui](https://realpython.com/python-strings/)

### **Integer** Type

In [ ]:
Reports_of_hepatitis_A = 10

print(Reports_of_hepatitis_A)

10


### **Float** Type



In [ ]:
Reports_of_hepatitis_A = 10

PopulationSize = 5000
Constant = 1000
Incidencia_de_Hepatite = Reports_of_hepatitis_A/PopulationSize

print('hepatitis-A Incidence for a given population is', Incidencia_de_Hepatite*Constant, '/', Constant, ' inhabitants')

hepatitis-A Incidence for a given population is 2.0 / 1000  inhabitants


### **Bool** Type

In [ ]:
I_am_a_bool = True
Also_a_bool = False

print(I_am_a_bool, type(Also_a_bool))

True <class 'bool'>




---



---



---



## 2) **Non-Primitive** Type:
    
These are types that are composed of other **primitive** types:


---



---


  Example:

  * **string** is a **non-primitive** type of **char**

  * **Tuples** is an **imutable** data collection of other **primitive** types. A **Tuple** can be composed of **heterogeneous** or **homogeneous** instances).

  * **list** is a **mutable** data collection **non-ordered** (of **heterogeneous** or **homogeneous**); **list** is stored non-sequentially in the memory.

  * **array** is an **ordered**, **single-typed** and **mutable** data collection. It is stored sequentially in the memory.

  * **sets** is a group of **unique** (without repetition) of **heterogeneous** or **homogeneous** instances.

  * **dict** is a type of **hash** object, always relating a **chave** to a **value**



## Tuples

They are immutable.

In [ ]:
Tuple = (1, 1 ,2, 15, 1.194, 'Hello')

print(Tuple, Tuple.count(1))

(1, 1, 2, 15, 1.194, 'Hello') 2


In [ ]:
print('New value at 3° position: ', Tuple[3])

# Let's try to change the value within the third position now
try:
  Tuple[3] = 999
except Exception as err:
  print(err)


New value at 3° position:  15
'tuple' object does not support item assignment


## List

First-in, First to get out

In [ ]:
# Bottom -> 1 -> 2 -> 3 -> 4 -> 5 (Top)
stack = [1,2,3,4,5]
stack.append('I am the last element of the stack') # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 -> 6 (Top)

print(stack, '\n\n ')

primeiro_a_sair = stack.pop()

print('The first element that got out of the stack: \n\n\t', primeiro_a_sair)

[1, 2, 3, 4, 5, 'Eu sou o último elemento que entrou nesta lista'] 

 
O primeiro que saiu da lista é: 

	 Eu sou o último elemento que entrou nesta lista


## Arrays

Arrrays are the base blocks for mathematical/statistical studies.

In Python, we use arrays from the **numpy** package, which is compiled in C++, optimizing computer processings.



In [ ]:

import numpy as np

Array = np.array([1,2,3,4,5,6])


Array2 = np.array([2,2,2,2,2,2])


print('Matricial operations:    ', Array * Array2)


# Realizando uma operação de Broadcasting:

print('Broadcasting operations: ', Array * 2)



# Slicing data
print('Slicing: ', Array[:3])



# Transpose operations:
Array = np.arange(9).reshape(3,3)
print('original: \n', Array)
print('transpose  : \n', Array.T)



Operação matricial:     [ 2  4  6  8 10 12]
Operação Broadcasting:  [ 2  4  6  8 10 12]
Operação de slicing  :  [1 2 3]
Array original: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Operação de transpose  : 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


## Sets

In [ ]:
x_set = set('CAKE&COKE')

print('Meu set: ', x_set)

y_set = set('COOKIE')

#All elements in x_set that are not in y_set

print('Exclusion of y over x: ', x_set - y_set)

print('Exclusion of x over y: ', y_set - x_set)

# Union
print('Union: ', x_set|y_set)

# Intersection

print('Intersection: ', x_set & y_set)


Meu set:  {'C', 'K', 'O', '&', 'E', 'A'}
Exclusão de y sobre x:  {'&', 'A'}
Exclusão de x sobre y:  {'I'}
União:  {'C', 'K', 'I', 'O', '&', 'E', 'A'}
Intersecção:  {'K', 'E', 'O', 'C'}


## Dict



*   Addition of new **labels**
*   Alteration of != entries



In [ ]:

PhoneList = {'Joao':'1111-1111',
                    'Gabriel':'1111-1112',
                    'Maria':'2222-2223',
                    'List':[1,2,3,True, 'asvoasd']
                    }

print(PhoneList)


{'Joao': '1111-1111', 'Gabriel': '1111-1112', 'Maria': '2222-2223', 'Lista': [1, 2, 3, True, 'asvoasd']}


In [ ]:

# Agora, será que podemos ser mais ousados, e pensar que dicionários são equivalentes a Planilhas de um de Excel?

Excel = {'Column_1':[1,2,3,4],
         'Column_2':[1,2,3,4],
         'Column_3':[1,2,3,4],
         'Column_4':[1,2,3,4],
         'Column_5':[1,2,3,4]}


Excel2 = {'Column_1':[1,2,3,4],
          'Column_2':[1,2,3,4],
          'Column_3':[1,2,3,4],
          'Column_4':[1,2,3,4],
          'Column_5':[1,2,3,4]}


Excel3 = {'Column_1':[1,2,3,4],
          'Column_2':[1,2,3,4],
          'Column_3':[1,2,3,4],
          'Column_4':[1,2,3,4],
          'Column_5':[1,2,3,4]}


In [ ]:
# E se meu Excel tiver Diferentes Abas, e cada aba tivesse uma Planilha de um de Excel?

Excel_withTabs = {'Tab1':Excel,
                  'Tab2':Excel2,
                  'Tab3':Excel3}

print(Excel_withTabs)

{'Aba1': {'Coluna_1': [1, 2, 3, 4], 'Coluna_2': [1, 2, 3, 4], 'Coluna_3': [1, 2, 3, 4], 'Coluna_4': [1, 2, 3, 4], 'Coluna_5': [1, 2, 3, 4]}, 'Aba2': {'Coluna_1': [1, 2, 3, 4], 'Coluna_2': [1, 2, 3, 4], 'Coluna_3': [1, 2, 3, 4], 'Coluna_4': [1, 2, 3, 4], 'Coluna_5': [1, 2, 3, 4]}, 'Aba3': {'Coluna_1': [1, 2, 3, 4], 'Coluna_2': [1, 2, 3, 4], 'Coluna_3': [1, 2, 3, 4], 'Coluna_4': [1, 2, 3, 4], 'Coluna_5': [1, 2, 3, 4]}}


# And what about complex objects?

## **Custom classes**:


### Examplo: Sub 20 Futeball team :

In [ ]:
class Sub20FutballTeam(dict):
  def __setitem__(self, key, idade:int):
    if idade > 20:
      raise TypeError('{0} could not be put into the team. This person is {1} years old'.format(key, idade))
    else:
      return dict.__setitem__(self, key, idade)

Sub20 = Sub20FutballTeam()

Sub20['Joao'] = 18

Sub20['Gabriel'] = 19

Sub20

{'Gabriel': 19, 'Joao': 18}

In [ ]:
# Now, let's try to add some players that are above 20 years,
# and see what happens

Sub20['Pelé'] = 65
Sub20['Romário'] = 18

TypeError: ignored