# Introdução à Programação usando Python

Por: Philipe Riskalla Leal

data: 31/08/2023

# Tipos de Objetos

## Classificações

* Por Mutabilidade

* Por Derivação (variáveis primitivas e derivadas)

# Classificação de Variáveis segundo critério de mutabilidade



> ## Mutáveis
  *   Date (data)
  *   Time (tempo)
  *   DateTime (data-tempo)
  *   TimeDelta (deslocamento temporal)
  *   Bool (booleano)
  *   Set (conjunto)
  *   Dictionary (dicionário)
  *   List (lista)
  *   Array (sequência de objetos virtualmente contíguos na memória)
  *   Function (função)



> ## Imutáveis
*   Strings (textos)
*   Tuple (tupla)
*   Byte (bite)
*   Integers (inteiros)
*   Float (números de ponto flutuante (e.g., reais) com X bits de precisão)
*   Complex (números complexo)
*   FronzenSet (conjunto imutável)

# Tipos de Objeto Customizados (user defined)
*   Class (classes)



---

---

---

    

## Date, Time, DateTime e TimeDelta


In [ ]:
from datetime import date, timedelta, datetime, time
import calendar

MinhaData = date.today()
print(f"Hoje é: {MinhaData}")

Hoje é: 2023-08-31


In [ ]:
ano = 2015
mes = 4
dia = 6

DiaQualquer = date(ano, mes, dia)

print(f"Dia selecionado: {DiaQualquer}")

print(f"O ano desta data informada é bissexto? \n\t Resposta: {calendar.isleap(DiaQualquer.year)}")

Dia selecionado: 2015-04-06
O ano desta data informada é bissexto? 
	 Resposta: False


In [ ]:
# Adicionando comentários no meio do código


# Vamos adicionar um determinado número de dias à nossa data inicial:
dt = timedelta(days=4, weeks=1)

print("Time delta ==  ", dt)

NovaData = DiaQualquer + dt

print(f"Após adicionar 4 dias e 1 semana, temos {NovaData}")


Time delta ==   11 days, 0:00:00
Após adicionar 4 dias e 1 semana, temos 2015-04-21


In [ ]:
ano = 2025
mes = 4
dia = 6
hora = 4
minuto = 59
segundo = 59
microsegundo = 123_456
DataTempo = datetime(ano, mes, dia, hora, minuto, segundo, microsegundo)

print("Minha data Tempo: ", DataTempo.strftime("dia %d/%m/%Y às %H:%M:%S e %f milisegundos"))

Minha data Tempo:  dia 06/04/2025 às 04:59:59 e 123456 milisegundos


## Booleano (verdadeiro ou falso)

In [ ]:
meuBooleanoFalso = False

meuBooleanoVerdadeiro = True

if meuBooleanoVerdadeiro:
  print("Eu sou verdadeiro")

print()

if not meuBooleanoFalso:
  print("Eu sou falso")

Eu sou verdadeiro

Eu sou falso



---

---

---

## Set (conjunto)

Um conjunto somente aceita valores únicos (não repetidos)

In [ ]:
meuConjunto = set()

meuConjunto.add(1)

meuConjunto.add(2)

meuConjunto.add(3)

meuConjunto.add("Coxinha")

meuConjunto.add("Abóbora")

meuConjunto.add("laranja")

meuConjunto.remove("laranja")

meuConjunto

{1, 2, 3, 'Abóbora', 'Coxinha'}

In [ ]:
outroConjunto = set()

outroConjunto.add("Abóbora")
outroConjunto.add("Coxinha")
outroConjunto.add("Maracujá")

interseccao = meuConjunto.intersection(outroConjunto)
conjuntoDiferenca = meuConjunto.difference(outroConjunto)

print(type(interseccao), interseccao)

# Notar que a string "Maracujá" não faz parte destae conjunto diferença,
# pois este conjunto diferença é sempre tomado como
# base o conjunto da esquerda da operação

print(type(conjuntoDiferenca), conjuntoDiferenca, )

# Para considerar a diferença de ambos conjuntos, devemos utilizar a lógica de
# diferença simétrica
# neste caso, notar que a string "Maracujá" é retornada pela função.
conjuntoDiferencaSimetrica = meuConjunto.symmetric_difference(outroConjunto)

print(type(conjuntoDiferencaSimetrica), conjuntoDiferencaSimetrica)

<class 'set'> {'Coxinha', 'Abóbora'}
<class 'set'> {1, 2, 3}
<class 'set'> {1, 2, 3, 'Maracujá'}


## Dictionary (dicionário)

Dicionários são compostos por uma chave e um valor (key, value)

In [ ]:
# Tipos de Inicialização do dicionário

  ## Opção 1
listaDeTelefone = dict()

  ## Opção 2
listaDeTelefone = {}

listaDeTelefone["Philipe"] = "9-9997 1234"
listaDeTelefone["Maria"] = "9-9997 1235"
listaDeTelefone["Joao"] = "9-9997 1233"

print(listaDeTelefone, end="\n\n")

print(f"Qual é o telefone do Philipe? \n\t Resposta: {listaDeTelefone['Philipe']}")




{'Philipe': '9-9997 1234', 'Maria': '9-9997 1235', 'Joao': '9-9997 1233'}

Qual é o telefone do Philipe? 
	 Resposta: 9-9997 1234


In [ ]:
# Exemplo 2 de dicionários


meuDicionario = dict()

meuDicionario[0] = 0
meuDicionario[1] = 10
meuDicionario[2] = 20
meuDicionario[3] = 30


outroDicionario = {4:40, 5:50}



print("meuDicionario: ", meuDicionario)
print("outroDicionario: ", outroDicionario)

meuDicionarioCopia = meuDicionario.copy()

meuDicionarioCopia.update(outroDicionario)

print(meuDicionario)
print("União de dicionarios: ", meuDicionarioCopia)

meuDicionario:  {0: 0, 1: 10, 2: 20, 3: 30}
outroDicionario:  {4: 40, 5: 50}
{0: 0, 1: 10, 2: 20, 3: 30}
União de dicionarios:  {0: 0, 1: 10, 2: 20, 3: 30, 4: 40, 5: 50}


# List (lista)

definição: sequência de objetos quaisquer de tamanho **variável** **não-contiguamente** armazenados na memória do computador.

In [ ]:
Lista = list()

Lista = []


for i in range(1, 11):
  Lista.append(i)

print("1° Elemento da lista: ", Lista[0])

print("Último Elemento da lista: ", Lista[-1])

print("Número total de Elementos na lista: ", len(Lista))

1° Elemento da lista:  1
Último Elemento da lista:  10
Número total de Elementos na lista:  10


## Array (sequência de objetos virtualmente contíguos na memória)

Segundo a Álgebra Linear, um array pode ser visto como Vetor, uma Matriz, ou genericamente como um Tensor

In [ ]:
import numpy as np

array = np.array([1,2,3,4])

print("Tamanho do array: ", len(array))

print("Tamanho do array: ", array.size)

print("Dimensão do array: ", array.ndim)

# alterando o shape de um array
  # neste exemplo, adicionamos mais uma dimensão a este array
arrayReshaped = array.reshape(-1, 1)
print("arrayReshaped: \n", arrayReshaped)
print("Tamanho do array remoldado: ", len(arrayReshaped))
print("Tamanho do array remoldado: ", arrayReshaped.size)
print("Dimensão do array remoldado: ", arrayReshaped.shape)

Tamanho do array:  4
Tamanho do array:  4
Dimensão do array:  1
arrayReshaped: 
 [[1]
 [2]
 [3]
 [4]]
Tamanho do array remoldado:  4
Tamanho do array remoldado:  4
Dimensão do array remoldado:  (4, 1)


In [ ]:
Array2D = np.array([[1,2,3], [4,5,6]])

print(Array2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
Array3D = np.array([[[1,2,3], [4,5,6]],
                    [[7,8,9], [10,11,12]]
                    ])

print(Array3D)
print()
print("Shape do array 3D: ", Array3D.shape)
print("Dimensões do array 3D: ", Array3D.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape do array 3D:  (2, 2, 3)
Dimensões do array 3D:  3


### Operações sobre Arrays



*   Adição com escalar
*   Subtração com escalar
*   Multiplicação com escalar
*   Divisão com escalar
*   Multiplicação de Matrizes
  *    Produto Interno
  *    Produto escalar (numpy.dot)
*   Álgebra Linear
   *   Matriz Inversa
   *   Transposição de Matriz    
   *   Solução de Equação


In [ ]:
# adição de escalar

vector = np.array([2,4,6])
Resultante = vector + 3

print(Resultante)

[5 7 9]


In [ ]:
# subtração de escalar

vector = np.array([2,4,6])
Resultante = vector - 3

print(Resultante)


[-1  1  3]


In [ ]:
# multiplicação com escalar

vector = np.array([2,4,6])
Resultante = vector * 3

print(Resultante)

print()
# temos o mesmo resultado, se multiplicarmos por um array de tamanho 1
Resultante = vector * np.array([3])

print(Resultante)

[ 6 12 18]

[ 6 12 18]


In [ ]:
# divisão com escalar

vector / 10

array([0.2, 0.4, 0.6])

### Multiplicação entre Matrizes

M x A

Multiplicação Ponto a Ponto (elemento a elemento)

In [ ]:
# multiplicação com matrizes

END = "\n\n"


# Criação da Matriz de dimensões 3x3

matrix = np.array([[2,2,2],[4,4,4],[6,6,6]])
print("Matriz: \n", matrix, end=END)

# Criação do Vetor de dimensões 3x1
vector = np.array([[2,4,6]]).T

vector = np.array([[2],[4],[6]])


print("vector: \n", vector, end=END)

# Extraindo os resultado da multiplicação entre matrizes
matrixResultante = matrix * vector

print(f"Dimensões: \n\t matrix: {matrix.shape}, \n\t vector: {vector.shape}, \n\t matrix: {matrixResultante.shape}", end=END)
print("matrixResultante: \n", matrixResultante)

Matriz: 
 [[2 2 2]
 [4 4 4]
 [6 6 6]]

vector: 
 [[2]
 [4]
 [6]]

Dimensões: 
	 matrix: (3, 3), 
	 vector: (3, 1), 
	 matrix: (3, 3)

matrixResultante: 
 [[ 4  4  4]
 [16 16 16]
 [36 36 36]]


Multiplicação Interna entre Matrizes

np.inner(a, b) = sum(a[:]*b[:])

referência: [aqui](https://numpy.org/doc/stable/reference/generated/numpy.inner.html)

In [ ]:
a = np.array([1,2,3])
b = np.array([0,1,0])

# Resultado = (1*0 + 2*1 + 3*0)
Resultado = np.inner(a, b)

print(Resultado)



2


In [ ]:
# divisão de matrizes
matrixDivisao = matrix / vector
print(matrixDivisao)

[[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]




---



---



---



## Álgebra Linear
   *   Matriz identidade
   *   Matriz Inversa
   *   Transposição de Matriz    
   *   Solução de Equação

In [ ]:
# Extraindo a Matriz identidade

Identidade = np.eye(matrix.shape[0])

# Produto Escalar
produtoEscalar_MI = matrix.dot(Identidade)
print(produtoEscalar_MI)

produtoEscalar_IM = Identidade.dot(matrix)

# Verificação de Permutação
PermutacaoEhIgual = np.all(produtoEscalar_MI == produtoEscalar_IM)

print(f"\n A permutação altera o produto? {~PermutacaoEhIgual}")

[[2. 2. 2.]
 [4. 4. 4.]
 [6. 6. 6.]]

 A permutação altera o produto? False


In [ ]:
# Matriz Inversa (se houver)

a = np.array([[1., 2.], [3., 4.]])
ainv = np.linalg.inv(a)
condicao = np.allclose(np.dot(a, ainv), np.eye(2))

print("Matriz original: ", matrix)

print(ainv)

print(f"Matriz 'A' vezes matriz 'Ainv' == matriz Identidade de A? \n\t Resposta: {condicao}")



Matriz original:  [[ 1  2  3]
 [ 4  4  4]
 [ 3  6 12]]
[[-2.   1. ]
 [ 1.5 -0.5]]
Matriz 'A' vezes matriz 'Ainv' == matriz Identidade de A? 
	 Resposta: True


In [ ]:
# Transposta de matrizes

A = np.array([[1,2,3], [4,5,6]])

print("Matriz original: \n", A, end=END)

print("Matriz transposta: \n", A.T, end=END)


Matriz original: 
 [[1 2 3]
 [4 5 6]]

Matriz transposta: 
 [[1 4]
 [2 5]
 [3 6]]



## Solução de Equações

  *    Equações determinadas
  *    Equações sobre-determinadas (há mais equações do
que variáveis)


### Sistema de Equações determinadas

${
f(x)=
\begin{cases}
x0 + 2 * x1 = 1 ,  \hspace{35pt} \text{eq 1 }\\
3 * x0 + 5 * x1 = 2 ,  \hspace{20pt} \text{eq 2 }
\end{cases}
}$

In [ ]:
# Equações determinadas
eq1 = [1, 2]
eq2 = [3, 5]

ladoEsquerdoDaIgualdade =  np.array([eq1,
                                     eq2])

ladoDireitoDaIgualdade = np.array([1, 2])
Resultado = np.linalg.solve(ladoEsquerdoDaIgualdade, ladoDireitoDaIgualdade)
x0, x1 = Resultado
print(f"Valores: \n\t x0 = {round(x0)} \n\t x1 = {round(x1)}")

Valores: 
	 x0 = -1 
	 x1 = 1


## Equações sobre-determinadas (há mais equações do que variáveis)

Este tipo de situação envolve casos, por exemplo, em que buscamos traçar uma reta entre nossos pontos amostrais.

### Exemplo de caso:

$y = mx + c$

$x = [0, 1, 2, 3]$ => pontos amostrais da variável independente

$y = [-1, 0.2, 0.9, 2.1]$ => pontos amostrais da variável dependente





In [ ]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])

# dado que nossa equação f(x) aceita um coeficiente linear (i.e., o "c" do (fx)), devemos adicionar
# uma coluna unária (cheia de 1s).

A = np.vstack([x, np.ones(len(x))]).T

m, c = np.linalg.lstsq(A, y, rcond=None)[0]

print(f'Resposta: a equação linear da função é igual a "y = {round(m,2)}*x + {round(c, 2)}"')

Resposta: a equação linear da função é igual a "y = 1.0*x + -0.95"


## Funções

In [ ]:
def adicionaValor(x, valor):
  return x + valor

print(adicionaValor(2, 10))

print(adicionaValor(4, 10))

def identidade(x):
  return x

print(identidade("Ola"), identidade(" mundo"))


12
14
Ola  mundo



## Funções identadas

In [ ]:
def funcaoDentroDeFuncao():

  def funcaoInterna():
    return 2

  def funcaoInterna2():
    return 3

  return funcaoInterna() + funcaoInterna2()

funcaoDentroDeFuncao()

5

## Funções recursivas

In [ ]:
def fibonaccy(n: int = 4):
  sequenciaFibonaccy = []
  penultimo=1
  ultimo=1

  if (n==1):
    sequenciaFibonaccy.append(penultimo)

  elif (n==2):
    sequenciaFibonaccy.append(penultimo)
    sequenciaFibonaccy.append(ultimo)

  else:
    sequenciaFibonaccy.append(penultimo)
    sequenciaFibonaccy.append(ultimo)


    while n >= 3:
      resultado = ultimo + penultimo
      penultimo = ultimo
      ultimo = resultado
      n -= 1
      sequenciaFibonaccy.append(resultado)

  for i in sequenciaFibonaccy:
    print(i)

  return sequenciaFibonaccy[-1]



print(fibonaccy(10))

1
1
2
3
5
8
13
21
34
55
55
--------------------------------------------------
55


In [ ]:
# versão recursiva

def fibonaccyRecursiva(n: int = 4, sequenciaFibonaccy = []):

  if (n==1):
    return 1

  elif (n==2):
    return 1

  else:
    return fibonaccyRecursiva(n -1) + fibonaccyRecursiva(n-2)

print(fibonaccyRecursiva(10))


## Imutáveis


*   Strings (textos)
*   Tuple (tupla)
*   Integers (inteiros)
*   Float (números de ponto flutuante (e.g., reais) com X bits de precisão)
*   Complex (números complexo)
*   FronzenSet (conjunto imutável)

# Strings

Definição: Conjunto de tamanho arbitrário de letras (*characters*).

Exemplos:

    "esta é uma string"

    "esta é uma outra string"

    "string"

    "Hello World"

Tuple (tupla)

In [ ]:
Tupla = (1,2,3)

for i in Tupla:
  print(i)

1
2
3


In [ ]:
# Tuplas são imutáveis:

try:
  Tupla[0] = Tupla[0] + 1
except Exception as err:
  print(err)

'tuple' object does not support item assignment


# Integer (inteiro) e Float (ponto flutuante)

In [ ]:
from numbers import Integral

Integer = int(5)

Integer2 = Integer + 2



print(isinstance(Integer, Integral))
print(Integer == Integer2)

True
False


In [ ]:
# Divisão de inteiros

resultado = 4/2

print(type(resultado), resultado)


resultado = 4//2

print(type(resultado), resultado)

<class 'float'> 2.0
<class 'int'> 2


# Números Complexos

In [ ]:
c= complex(real=10, imag=5)

(10+5j)

In [ ]:
imag = np.array([1+2j, 3+4j, 5+6j])

print(imag)

[1.+2.j 3.+4.j 5.+6.j]


## FronzenSet (conjunto imutável)

In [ ]:
fset = frozenset({10,2,4,"abóbora", "laranja"})

try:
  fset.add("Abacaxi")
except Exception as err:
  print("FrozenSets são imutáveis.")

FrozenSets são imutáveis.


---
---
---

# Tipos de Objeto Customizados

## Class (classes)

In [ ]:
class Pessoa:
  def __init__(self, nome, idade) -> None:
    self.nome = nome
    self.idade = idade

  def envelhecer(self) -> None:
    """Envelhece a pessoa em um ano.

    """
    self.idade = self.idade + 1


  def falar(self, x: str = None) -> str:
    """Fala"""

    if (x == None):
      x = f"Olá. Meu nome é {self.nome}. Eu tenho {self.idade} anos"
    return str(x)

  def morrer(self) -> None:
    """Deleta instância de Pessoa"""

    del self


In [ ]:
p1 = Pessoa("Philipe", 33)

print(p1.falar())


Olá. Meu nome é Philipe. Eu tenho 33 anos


In [ ]:

# Vamos envelhecer a pessoa
print(f"Idade de p1 => {p1.idade}")

p1.envelhecer()

# Verificando idade de P1 após envelhecimento
print(f"Idade de p1 => {p1.idade}")

Idade de p1 => 33
Idade de p1 => 34


## Exemplo de classe que representa um Time de futebol

In [ ]:
class Sub20FutballTeam(dict):
  def __setitem__(self, key, idade:int):
    if idade > 20:
      raise TypeError('{0} could not be put into the team. This person is {1} years old'.format(key, idade))
    else:
      return dict.__setitem__(self, key, idade)

Sub20 = Sub20FutballTeam()

Sub20['Joao'] = 18

Sub20['Gabriel'] = 19

Sub20['Murilo'] = 18

Sub20

{'Joao': 18, 'Gabriel': 19, 'Murilo': 18}

In [ ]:
# Now, let's try to add some players that are above 20 years,
# and see what happens

Sub20['Pelé'] = 65


TypeError: ignored

## Q&A

Como criar uma classe que consiga mapear todos os elementos (instâncias) desta mesma classe, assim como todos os elementos de classes filhas (derivadas) desta classe parental?



### [Solução](https://stackoverflow.com/questions/12101958/how-to-keep-track-of-class-instances)

sobre-escrever o método de instanciação (criação) da classe desejada.

In [22]:

class BaseClassWithMappingCapabilities(object):
    @classmethod
    def __new__(cls, *args, **kwargs):
        instance = object.__new__(cls)
        if "instances" not in cls.__dict__:
            cls.instances = list()
        if instance not in cls.instances:
          cls.instances.append(instance)

        return instance

class ChildClass(BaseClassWithMappingCapabilities):
  def __init__(self, nome: str) -> None:
      self.nome = nome

  def __repr__(self) -> str:
      return f"Nome: {self.nome}"


classesMapeadoras = [ChildClass(f"Instância {i}") for i in range(1, 11)]

c1 = classesMapeadoras[0]

for sibling in c1.instances:
    print(sibling)


Nome: Instância 1
Nome: Instância 2
Nome: Instância 3
Nome: Instância 4
Nome: Instância 5
Nome: Instância 6
Nome: Instância 7
Nome: Instância 8
Nome: Instância 9
Nome: Instância 10
