# Data Structure:

Referência: [Python Docs](https://docs.python.org/3/tutorial/datastructures.html)

Em **Python**, o dado pode ser gerenciado de diferentes formas; esta gestão impacta diretamente na rotina (algoritmo) utilizado.


# Classificação de Variáveis segundo critério de Derivação

  * **primitive-types** & **non-primitive-types**



---



---



---




## 1) **Primitive Types**


a)   Strings

b)   Integers (Inteiros)

c)   Float (fracionários)

d)   Boolean

**Observation**: Primitives store only one information per type.

### **String** Type


In [ ]:
I_am_String = 'Hi! My name is Philipe'

print(I_am_String)

Hi! My name is Philipe


Mais exemplos: [veja aqui](https://realpython.com/python-strings/)

### **Integer** Type

In [ ]:
Reports_of_hepatitis_A = 10

print(Reports_of_hepatitis_A)

10


### **Float** Type



In [ ]:
Reports_of_hepatitis_A = 10

PopulationSize = 5000
Constant = 1000
Incidencia_de_Hepatite = Reports_of_hepatitis_A/PopulationSize

print('hepatitis-A Incidence for a given population is', Incidencia_de_Hepatite*Constant, '/', Constant, ' inhabitants')

hepatitis-A Incidence for a given population is 2.0 / 1000  inhabitants


### **Bool** Type

In [ ]:
I_am_a_bool = True
Also_a_bool = False

print(I_am_a_bool, type(Also_a_bool))

True <class 'bool'>




---



---



---



## 2) **Non-Primitive** Type:
    
Tipos não primitivos são tipos de variáveis derivados de tipos primitivos


---



---


  Examplos:

  * **string** (**non-primitive** de **char**)

  * **Tuples**: coleção de dados **imutáveis** de outros tipos **primitivos**. Uma **Tuple** pode ser composta por instâncias **heterogêneas** (não é recomendado) ou  **homogeneas** (recomendado).

  * **list**: coleção de dados **mutáveis** de outros tipos quaisquer (**primitivos**, ou **derivados**). Uma **list** pode ser composta por instâncias **heterogêneas** (não é recomendado) ou  **homogeneas** (recomendado); **list** é armazenado em espaços não sequenciais de memória.

  * **array**: coleção de dados **ordenados**, **homo-tipadas** (*single-typed*) e **mutáveis**; **array** é armazenado em espaços **sequenciais** de memória.

  * **sets**: conjunto de elementos/instâncias **únicas** (sem repetição).. Um **sets** pode ser composto por instâncias **heterogêneas** (não é recomendado) ou  **homogeneas** (recomendado).

  * **dict** (também chamado de **hash** em outras linguagens); serve de dicionário que relaciona uma **chave** (única) a um **valor** (qualquer).



## Tuples

* Imutáveis

In [ ]:
Tuple = (1, 1 ,2, 15, 1.194, 'Hello')

print(Tuple, Tuple.count(1))

(1, 1, 2, 15, 1.194, 'Hello') 2


In [ ]:
print('New value at 3° position: ', Tuple[3])

# Let's try to change the value within the third position now
try:
  Tuple[3] = 999
except Exception as err:
  print(err)


New value at 3° position:  15
'tuple' object does not support item assignment


## List

* First-in, First to get out

* Mutáveis

In [5]:

stack = ["Philipe","Tiago","Gabriel","Mauricio","Jéssica"]
ultima_Pessoa_a_Entrar_Na_Lista = "Zelda"

stack.append(ultima_Pessoa_a_Entrar_Na_Lista) # (Bottom) 1 -> 2 -> 3 -> 4 -> 5 -> 6 (Top)

print(stack, '\n\n ')

primeira_Pessoal_a_Sair_Da_Lista = stack.pop()


print('Primeira pessoa que saiu da lista: \n\t', primeiro_a_sair, "\n")

print("A última pessoa a entrar na lista foi a primeira a sair?", end="\n\t")

if ultima_Pessoa_a_Entrar_Na_Lista == primeira_Pessoal_a_Sair_Da_Lista:
  print("sim")
else:
  print("não")

['Philipe', 'Tiago', 'Gabriel', 'Mauricio', 'Jéssica', 'Zelda'] 

 
Primeira pessoa que saiu da lista: 
	 Zelda 

A última pessoa a entrar na lista foi a primeira a sair?
	sim


## Arrays

Arrrays are the base blocks for mathematical/statistical studies.

Em Python, arrays advém da biblioteca **numpy**, compilada em C++, para uma máxima otimização do processamento.



In [ ]:

import numpy as np

Array = np.array([1,2,3,4,5,6])


Array2 = np.array([2,2,2,2,2,2])


print('Matricial operations:    ', Array * Array2)


# Realizando uma operação de Broadcasting:

print('Broadcasting operations: ', Array * 2)



# Slicing data
print('Slicing: ', Array[:3])



# Transpose operations:
Array = np.arange(9).reshape(3,3)
print('original: \n', Array)
print('transpose  : \n', Array.T)



Operação matricial:     [ 2  4  6  8 10 12]
Operação Broadcasting:  [ 2  4  6  8 10 12]
Operação de slicing  :  [1 2 3]
Array original: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Operação de transpose  : 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


## Sets

In [ ]:
x_set = set('CAKE&COKE')

print('Meu set: ', x_set)

y_set = set('COOKIE')

#All elements in x_set that are not in y_set

print('Exclusion of y over x: ', x_set - y_set)

print('Exclusion of x over y: ', y_set - x_set)

# Union
print('Union: ', x_set|y_set)

# Intersection

print('Intersection: ', x_set & y_set)


Meu set:  {'C', 'K', 'O', '&', 'E', 'A'}
Exclusão de y sobre x:  {'&', 'A'}
Exclusão de x sobre y:  {'I'}
União:  {'C', 'K', 'I', 'O', '&', 'E', 'A'}
Intersecção:  {'K', 'E', 'O', 'C'}


## Dict



*   Addition of new **labels**
*   Alteration of != entries



In [ ]:

PhoneList = {'Joao':'1111-1111',
                    'Gabriel':'1111-1112',
                    'Maria':'2222-2223',
                    'List':[1,2,3,True, 'asvoasd']
                    }

print(PhoneList)


{'Joao': '1111-1111', 'Gabriel': '1111-1112', 'Maria': '2222-2223', 'Lista': [1, 2, 3, True, 'asvoasd']}


## Dicionários de Dicionários
Agora, será que podemos ser mais ousados,
e pensar que dicionários são equivalentes
a Planilhas de um de Excel?

In [6]:


Planilha_1_do_Arquivo_Excel = {'Column_1':[1,2,3,4],
                              'Column_2':[1,2,3,4],
                              'Column_3':[1,2,3,4],
                              'Column_4':[1,2,3,4],
                              'Column_5':[1,2,3,4]}


Planilha_2_do_Arquivo_Excel = {'Column_1':[1,2,3,4],
                              'Column_2':[1,2,3,4],
                              'Column_3':[1,2,3,4],
                              'Column_4':[1,2,3,4],
                              'Column_5':[1,2,3,4]}


Planilha_3_do_Arquivo_Excel = {'Column_1':[1,2,3,4],
                              'Column_2':[1,2,3,4],
                              'Column_3':[1,2,3,4],
                              'Column_4':[1,2,3,4],
                              'Column_5':[1,2,3,4]}


In [8]:


Arquivo_Excel_xlsx = {'Planilha 1': Planilha_1_do_Arquivo_Excel,
                      'Planilha 2': Planilha_2_do_Arquivo_Excel,
                      'Planilha 3': Planilha_3_do_Arquivo_Excel}

print(Arquivo_Excel_xlsx)

{'Planilha 1': {'Column_1': [1, 2, 3, 4], 'Column_2': [1, 2, 3, 4], 'Column_3': [1, 2, 3, 4], 'Column_4': [1, 2, 3, 4], 'Column_5': [1, 2, 3, 4]}, 'Planilha 2': {'Column_1': [1, 2, 3, 4], 'Column_2': [1, 2, 3, 4], 'Column_3': [1, 2, 3, 4], 'Column_4': [1, 2, 3, 4], 'Column_5': [1, 2, 3, 4]}, 'Planilha 3': {'Column_1': [1, 2, 3, 4], 'Column_2': [1, 2, 3, 4], 'Column_3': [1, 2, 3, 4], 'Column_4': [1, 2, 3, 4], 'Column_5': [1, 2, 3, 4]}}


# Objetos Complexos (OOP)

## **Custom classes**:


### Examplo: Sub 20 Futeball team :

In [14]:
class Sub20FutballTeam(dict):
  def __setitem__(self, key, idade:int):
    if idade > 20:
      raise TypeError('{0} could not be put into the team. This person is {1} years old'.format(key, idade))
    else:
      return dict.__setitem__(self, key, idade)

  def show_all_players(self) -> None:
    """Imprime nome e idade de cada jogador no time"""

    print("\n", "Time:")
    for key, value in self.items():
        print(f"\t{key}: {value} anos")

    print()

Sub20 = Sub20FutballTeam()

Sub20['Joao'] = 18

Sub20['Gabriel'] = 19

Sub20.show_all_players()

# print(Sub20)



 Time:
	Joao: 18 anos
	Gabriel: 19 anos



{'Joao': 18, 'Gabriel': 19}

In [15]:
# Now, let's try to add some players that are above 20 years,
# and see what happens

Sub20['Pelé'] = 65
Sub20['Romário'] = 18

TypeError: ignored